default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Firebase Crashlytics"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  end

  desc "Deploy a new version to the Google Play Store"
  lane :internal do
    gradle(task: "clean bundleRelease")

    upload_to_play_store(
      track: "internal", # Change to "production" for prod releases
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      json_key: "./play-store-key.json", # important: match GitHub Actions path
      package_name: "com.meetpe"
    )
  end
end
